# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghrel < Formula
  desc ""
  homepage ""
  version "0.1.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/apigear-io/ghrel/releases/download/0.1.2/ghrel_0.1.2_darwin_arm64.tar.gz"
      sha256 "942d9167436f9d00175e2e54fc7a56c5a7f11352f58fa84d9ddd578d52fbd438"

      def install
        bin.install "ghrel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apigear-io/ghrel/releases/download/0.1.2/ghrel_0.1.2_darwin_amd64.tar.gz"
      sha256 "10ea53c6586e373a7b8e0046aca4cca30f0fba50c3cd754fd24de4a8cc0b5ac8"

      def install
        bin.install "ghrel"
      end
    end
  end
end
