# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apigear < Formula
  desc ""
  homepage ""
  version "0.51.0"

  on_macos do
    on_intel do
      url "https://github.com/apigear-io/cli/releases/download/v0.51.0/apigear_darwin_amd64.zip"
      sha256 "4fa6dd33f64e5b143100a7e08615fdaeb5342df9df5db9b81c370b9976b58dc9"

      def install
        bin.install "apigear"
      end
    end
    on_arm do
      url "https://github.com/apigear-io/cli/releases/download/v0.51.0/apigear_darwin_arm64.zip"
      sha256 "bb9b9f50faae043aaa40e0194ddeac4c093edcdcf3086390f0e1401a373a0dd8"

      def install
        bin.install "apigear"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apigear-io/cli/releases/download/v0.51.0/apigear_linux_amd64.zip"
        sha256 "242934524deb9f20ddea5adb04fa8383ba3af377a765d45090a8e7ba578196bf"

        def install
          bin.install "apigear"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apigear-io/cli/releases/download/v0.51.0/apigear_linux_arm64.zip"
        sha256 "c53451259921f92a0487d5782162638e7a86cf6643a65e077a61a45ea8041c27"

        def install
          bin.install "apigear"
        end
      end
    end
  end
end
