# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apigear < Formula
  desc ""
  homepage ""
  version "0.13.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apigear-io/cli-releases/releases/download/v0.13.7/apigear_0.13.7_darwin_amd64.tar.gz"
      sha256 "108cc37a445e521271305d7d46b1a7902b05e82a8bcb8865622aa33a165a0ff8"

      def install
        bin.install "apigear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apigear-io/cli-releases/releases/download/v0.13.7/apigear_0.13.7_darwin_arm64.tar.gz"
      sha256 "cf7213f21b01f7ce1ae147579b69f5ec949d8d5892ef36a76e90efbba4e2deb2"

      def install
        bin.install "apigear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apigear-io/cli-releases/releases/download/v0.13.7/apigear_0.13.7_linux_arm64.tar.gz"
      sha256 "93283a122bbf12b3a31ef9977a46f91fc24cbb1fedca7bce46c1c1f4c0781d97"

      def install
        bin.install "apigear"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apigear-io/cli-releases/releases/download/v0.13.7/apigear_0.13.7_linux_amd64.tar.gz"
      sha256 "2e6c9d680522387b91a56080e6af7d80449c9a8360e372d36bf5634db4fa1f73"

      def install
        bin.install "apigear"
      end
    end
  end
end
