# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghrel < Formula
  desc ""
  homepage ""
  version "0.1.8"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/apigear-io/ghrel-releases/releases/download/0.1.8/ghrel-releases_0.1.8_darwin_arm64.tar.gz"
      sha256 "2cdd1f5790f4f4b44e60bb1765419e967610bb06287efdaaaeefaffbeea8f66d"

      def install
        bin.install "ghrel-releases"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apigear-io/ghrel-releases/releases/download/0.1.8/ghrel-releases_0.1.8_darwin_amd64.tar.gz"
      sha256 "ee86c1bed0f74691f650af23a47a584f592a05536930765e896c301ce938777e"

      def install
        bin.install "ghrel-releases"
      end
    end
  end
end
